# Generated by Django 4.2.1 on 2023-05-25 20:13

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user', help_text='Enter username', max_length=255)),
                ('first_name', models.CharField(help_text='Enter first name', max_length=255)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=255)),
                ('email', models.EmailField(help_text='something@gmail.com', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='+375 (29) 123-45-67', max_length=20)),
                ('date_of_birth', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2005, 5, 29))])),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='travel.country')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonClimateDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, null=True)),
                ('season_name', models.CharField(choices=[('summer', 'summer'), ('winter', 'winter'), ('spring', 'spring'), ('autumn', 'autumn')], default='summer', max_length=6)),
                ('climate_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Trip', max_length=50)),
                ('duration', models.IntegerField(choices=[(1, '1 week'), (2, '2 weeks'), (4, '4 weeks')], default=1)),
                ('departure_date', models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('chosen_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='travel.hotel')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='climate_descriptions',
            field=models.ManyToManyField(related_name='countries', to='travel.seasonclimatedescription'),
        ),
    ]
