# Generated by Django 4.2.1 on 2023-05-22 09:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonClimateDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(choices=[('summer', 'summer'), ('winter', 'winter'), ('spring', 'spring'), ('autumn', 'autumn')], max_length=6)),
                ('climate_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='seasons',
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2005, 5, 26))]),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.AddField(
            model_name='country',
            name='climate_descriptions',
            field=models.ManyToManyField(related_name='countries', to='travel.seasonclimatedescription'),
        ),
    ]
