# Generated by Django 4.2.1 on 2023-05-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(null=True, upload_to='trip/'),
        ),
    ]
