# Generated by Django 4.2.1 on 2023-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_seasonclimatedescription_remove_country_seasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonclimatedescription',
            name='alias',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seasonclimatedescription',
            name='season_name',
            field=models.CharField(choices=[('summer', 'summer'), ('winter', 'winter'), ('spring', 'spring'), ('autumn', 'autumn')], default='summer', max_length=6),
        ),
    ]
