# Generated by Django 4.2.1 on 2023-05-23 09:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_seasonclimatedescription_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2005, 5, 27))]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 week'), (2, '2 weeks'), (4, '4 weeks')], default=1),
        ),
    ]
