# Generated by Django 4.2.1 on 2023-05-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_trip_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='total_cost',
            new_name='cost',
        ),
    ]
