# Generated by Django 4.2.1 on 2023-06-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_rename_total_cost_trip_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(default='trip/default.jpg', null=True, upload_to='trip/'),
        ),
    ]
