# Generated by Django 4.2.1 on 2023-06-03 13:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_trip_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
