# Generated by Django 4.2.1 on 2023-05-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_trips_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='_cost',
            new_name='cost',
        ),
    ]
